### ISSUE TITLE
关于互助码替换

### ISSUE THREAD

**Issue by ghost** [qq34347476/js_script#1]
这个 替换后，上车助力池的就无效了是吧，我 替换后，就收不到 助力池的助力了、、

**Comment by qq34347476** [comment]
这个是自己互助自己，互助池的车不搭嘎，如果你自己互助了自己，互助池的就用不上了……建议双保险，我都是两个都弄，互助池经常忘了上车……

**Comment by ghost** [comment]
我助力池上车了，但是替换了以后 ，我今天 助力池上车的 游戏 没有收到助力，明天再看看

**Comment by ghost** [comment]
> 我助力池上车了，但是替换了以后 ，我今天 助力池上车的 游戏 没有收到助力，明天再看看

互助池的在哪上车？我咋没听过
