### ISSUE TITLE
/submit_activity_codes jxcfd 从日志中未找到任何互助码...

### ISSUE THREAD

**Issue by RockZhou8** [qq34347476/js_script#2]
财富岛 是lxk最新的（自动git pull），也手动bash了cfd和format_share_code.js，前者日志里也能看到互助码，但是format_share_code.js 后提示“/submit_activity_codes jxcfd 从日志中未找到任何互助码...“ 其他互助码均正常获取。

**Comment by qq34347476** [comment]
已添加
