### ISSUE TITLE
关于一键替换互助码，适配替换

### ISSUE THREAD

**Issue by ghost** [qq34347476/js_script#3]
E大的镜像更新了一个 ： export_sharecodes.sh 按 config.sh 格式导出的互助码，同时支持导出互助模板
导致一件替换无法使用了，牛子有空看看

**Comment by qq34347476** [comment]
上午我维护下

**Comment by ghost** [comment]
看你这是更新好了吗 牛子

**Comment by qq34347476** [comment]
更新过了，那几个你自己点开看注释，要用哪个。。e大版本 是  nevinee_format.js
