### ISSUE TITLE
TypeError: Cannot read property 'nickname' of undefined，求助大神

### ISSUE THREAD

**Issue by kissfast** [qq34347476/js_script#5]
请问这个是什么错误？
看日志，很多脚本都出现了这个错误（从这里通过diy.sh下载的）

**Comment by kissfast** [comment]
比如，
京东价格保护, 错误!
TypeError: Cannot read property 'nickname' of undefined
    at /jd/scripts/ZCY01_jd_priceProtect.js:396:33

还有，类似的
❗️国际盲盒, 错误!
TypeError: Cannot read property 'message' of undefined
    at /jd/scripts/i-chenzhe_jd_gjmh.js:48:20944
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/i-chenzhe_jd_gjmh.js:49:5637)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by qq34347476** [comment]
脚本bug。。。用户名之类的找不到。。能用且用吧
